// Static Recruiting Bingo card library.
// These entries give us a consistent tone across the app and can be tweaked over time
// as we gather feedback from recruiters.

export type CardEntry = string;

const defaultRecruitingLibrary: CardEntry[] = [
  "Candidate ghosted after accepting offer",
  "Hiring manager changed the role mid-search",
  "Found a resume with Comic Sans",
  "Interview panel asked the wrong questions",
  "Offer declined because of counter-offer",
  "Stakeholder vanished before final round",
  "Reference never called back",
  "Urgent req put on indefinite hold",
  "Candidate asked for double the budget",
  "Discovered duplicate candidates from two agencies",
  "Scheduling ping-pong took all week",
  "Candidate insisted on camera off for onsite",
  "Intake meeting stretched to two hours",
  "Offer letter typo caught at the last minute",
  "Sourcing list mysteriously disappeared",
  "Manager requested five more interviews",
  "Role renamed three times",
  "Feedback arrived after the deadline",
  "Candidate brought their cat to the Zoom call",
  "New tool rollout broke all templates",
  "Offer renegotiated after signing",
  "Interview loop forgot to submit scores",
  "Executive skipped their own interview",
  "Prospect replied all with a meme",
  "Hiring freeze announced mid-cycle",
  "Background check delayed onboarding",
  "Candidate submitted a resume PDF with no text",
  "Employee referral never filled out the form",
  "Sourcing channel produced zero leads",
  "Inbox hit 1,000 unread messages",
  "Same candidate applied to every role",
  "Requisition opened before leveling decision",
  "Candidate asked for a remote role that isn't",
  "Manager sent conflicting salary bands",
  "Whiteboard tool crashed mid-session",
  "Candidate only wanted answers via SMS",
  "Product demo turned into therapy session",
  "Offer packet stuck in legal review",
  "Hiring committee met without notes",
  "Candidate mistook us for a different company",
  "Candidate no-shows",
  "Candidate running late",
  "Candidate forgotten role",
  "Camera 'not working'",
  "Audio issues again",
  "Join from a moving car",
  "Pet cameo on camera",
  "Unexpected background",
  "Mute mishap moment",
  "Candidate early arrival",
  "Candidate late arrival",
  "Wrong meeting link",
  "Both in different links",
  "Screen share fails",
  "Zoom reboot needed",
  "Awkward long silence",
  "Talking while muted",
  "Can you see my screen?",
  "WiFi drop mid-call",
  "Echo on the call",
  "Resume formatting chaos",
  "Duplicate application",
  "ChatGPT cover letter",
  "Salary mismatch noted",
  "Forgot interview today",
  "Role mix-up moment",
  "JD not read yet",
  "Asks for remote again",
  "Unexpected salary ask",
  "Location unclear",
  "Calendar double-booked",
  "Last-minute cancel",
  "Interviewer running late",
  "Interviewer no-shows",
  "Scorecard missing",
  "Feedback very brief",
  "Panel didn't read resume",
  "Wrong question asked",
  "Extra interview added",
  "Interview goes over",
  "Req put on hold",
  "Req reopened suddenly",
  "JD updated again",
  "Unicorn request noted",
  "Scope changed mid-call",
  "Band still in review",
  "Offer packet delay",
  "New approval needed",
  "Reschedule requested",
  "Tool crash mid-call",
  "Whiteboard freeze",
  "ATS slow today",
  "ATS glitch strike",
  "Pipeline reshuffle",
  "Prospect replies all",
  "Wrong template sent",
  "Timezone confusion",
  "Slack “quick chat?”",
  "Email thread too long",
  "Unexpected PTO update",
  "Counter-offer hint",
  "Start date question",
  "Offer detail tweak",
  "More profiles requested",
  "Hiring freeze rumor",
  "Priority shift again",
  "New urgent req",
  "Manager name mix-up",
  "Doc missing suddenly",
  "Form needs update",
  "New process change",
  "Calendar chaos",
  "“Let's sync later”",
  "Unexpected ping",
  "Live sync delay",
  "Late feedback again",
  "Meeting overrun",
  "Team channel noise",
  "Browser cache fix",
  "Tool login loop",
  "Duplicate req found",
  "Ping during call",
  "Quick Slack follow-up",
  "Candidate asks timeline",
  "Manager asks pipeline",
  "Sourcing list update",
  "Boolean tweak needed",
  "LinkedIn throttle",
  "Fresh pipeline added",
  "Ref check ping",
  "Reminder email needed",
  "“Any update?” DM",
  "Calendar rename",
  "New note added",
  "Unexpected laugh moment",
  "Coffee break needed",
  "Team meme posted",
  "Perfect timing ping",
  "Meeting ends on time",
  "Surprise good news"
];

export function getDefaultRecruitingLibrary(): CardEntry[] {
  return [...defaultRecruitingLibrary];
}
